### ISSUE TITLE
Use flat config format

### ISSUE THREAD

**Issue by jhnns** [peerigon/eslint-config-peerigon#101]
https://eslint.org/blog/2022/08/new-config-system-part-2/

**Comment by jhnns** [comment]
Implementation has started on https://github.com/peerigon/eslint-config-peerigon/tree/eslint-9

There are a couple of plugins that don't have ESLint 9 support yet:

- [ ] eslint-plugin-import https://github.com/peerigon/eslint-config-peerigon/issues/143
- [ ] eslint-plugin-promise https://github.com/eslint-community/eslint-plugin-promise/issues/449
- [ ] eslint-plugin-react https://github.com/jsx-eslint/eslint-plugin-react/issues/3699

We don't necessarily have to wait for all of them because we might switch some dependencies (e.g. switching out eslint-plugin-promise with eslint-plugin-unicorn which also has some promise rules). However, I would definitely wait for eslint-plugin-react as there is not a good alternative afaik.

**Comment by karlhorky** [comment]
Hey @jhnns! 👋  It's possible to migrate now using the Compatibility Utilities, in case you want to try it out: 

- https://x.com/karlhorky/status/1792500811307622631
